<HTML>
<HEAD>
!IF @.TITLE
<TITLE>${@.XREF}: ${@.NAME} (${@.TITLE})</TITLE>
!ELSE
<TITLE>${@.XREF}: ${@.NAME}</TITLE>
!ENDIF
</HEAD>
<BODY>
!IF @.TITLE
<H1><A HREF=\"${@.&}\">${@.NAME} (${@.TITLE})</A></H1>
!ELSE
<H1><A HREF=\"${@.&}\">${@.NAME}</A></H1>
!ENDIF
!INCLUDE @.img
!IF @.EVENT
<UL>
!RESET i
!WHILE @.EVENT[i]
!IF @.EVENT[i].DATE
!IF @.EVENT[i].PLACE
<LI><EM>${@.EVENT[i].TAG}</EM>: ${@.EVENT[i].DATE}, ${@.EVENT[i].PLACE.NAME}
!ELSE
<LI><EM>${@.EVENT[i].TAG}</EM>: ${@.EVENT[i].DATE}
!ENDIF
!ELSE
<LI><EM>${@.EVENT[i].TAG}</EM>: ${@.EVENT[i].PLACE.NAME}
!ENDIF
!INCREMENT i
!END
</UL>
!ENDIF
!IF @.FATHER
<EM>Father:</EM> <A HREF="${@.FATHER.XREF.&}">${@.FATHER.NAME}</A><BR>
!ENDIF
!IF @.MOTHER
<EM>Mother:</EM> <A HREF="${@.MOTHER.XREF.&}">${@.MOTHER.NAME}</A><BR>
!ENDIF
<BR>
!RESET i
!WHILE @.FAMS[i]
</EM>Family ${i}</EM>:
!IF @.ISMALE
!IF @.FAMS[i].FAMILY.WIFE
<A HREF="${@.FAMS[i].FAMILY.WIFE.XREF.&}">${@.FAMS[i].FAMILY.WIFE.NAME}</A>
!ENDIF
!ENDIF
!IF @.ISFEMALE
!IF @.FAMS[i].FAMILY.HUSBAND
<A HREF="${@.FAMS[i].FAMILY.HUSBAND.XREF.&}">${@.FAMS[i].FAMILY.HUSBAND.NAME}</A>
!ENDIF
!ENDIF
!IF @.FAMS[i].FAMILY.EVENT
<UL>
!RESET j
!WHILE @.FAMS[i].FAMILY.EVENT[j]
<LI><EM>${@.FAMS[i].FAMILY.EVENT[j].TAG}</EM>: ${@.FAMS[i].FAMILY.EVENT[j].DATE}, ${@.FAMS[i].FAMILY.EVENT[j].PLACE.NAME}
!INCREMENT j
!END
</UL>
!ELSE
<BR>
!ENDIF
!IF @.FAMS[i].FAMILY.CHILDREN
<OL>
!RESET j
!WHILE @.FAMS[i].FAMILY.CHILDREN[j]
<LI><A HREF="${@.FAMS[i].FAMILY.CHILDREN[j].INDIV.XREF.&}">${@.FAMS[i].FAMILY.CHILDREN[j].INDIV.NAME}</A>
!INCREMENT j
!END
</OL>
!ENDIF
!INCREMENT i
!END
<BR>
<A HREF="INDEX.html">INDEX</A><BR><BR>
!IF @.NOTE
<H2>Notes</H2>
!RESET i
!WHILE @.NOTE[i]
${@.NOTE[i].TEXT}
!RESET j
!WHILE @.NOTE[i].CONT[j]
${@.NOTE[i].CONT[j].TEXT}
!INCREMENT j
!END
<BR>
!INCREMENT i
!END
!ENDIF
<BR>
!IF @.SOURCE
<H2>Sources</H2>
!RESET i
!WHILE @.SOURCE[i]
${@.SOURCE[i].SOURCE.TEXT}
!RESET j
!WHILE @.SOURCE[i].SOURCE.CONT[j]
${@.SOURCE[i].SOURCE.CONT[j].TEXT}
<BR>
!INCREMENT j
!END
<BR>
!INCREMENT i
!END
!ENDIF
!INCLUDE @.inc
</BODY>
</HTML>
